#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThiTracNghiem_Son
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TracNghiem")]
	public partial class DataTracNghiemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
        public System.DateTime GetServerDate()
        {
            //return ((System.DateTime)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
            return ExecuteQuery<DateTime>("SELECT GETDATE()").First();
        }
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChuDe(ChuDe instance);
    partial void UpdateChuDe(ChuDe instance);
    partial void DeleteChuDe(ChuDe instance);
    partial void InsertCauHoi(CauHoi instance);
    partial void UpdateCauHoi(CauHoi instance);
    partial void DeleteCauHoi(CauHoi instance);
    partial void InsertDeThi(DeThi instance);
    partial void UpdateDeThi(DeThi instance);
    partial void DeleteDeThi(DeThi instance);
    partial void InserttaiKhoan(taiKhoan instance);
    partial void UpdatetaiKhoan(taiKhoan instance);
    partial void DeletetaiKhoan(taiKhoan instance);
    partial void InsertBatDau(BatDau instance);
    partial void UpdateBatDau(BatDau instance);
    partial void DeleteBatDau(BatDau instance);
    partial void InsertKhoi(Khoi instance);
    partial void UpdateKhoi(Khoi instance);
    partial void DeleteKhoi(Khoi instance);
    partial void InsertNien_khoa(Nien_khoa instance);
    partial void UpdateNien_khoa(Nien_khoa instance);
    partial void DeleteNien_khoa(Nien_khoa instance);
    partial void InsertTaiKoan_H(TaiKoan_H instance);
    partial void UpdateTaiKoan_H(TaiKoan_H instance);
    partial void DeleteTaiKoan_H(TaiKoan_H instance);
    partial void InsertDe_H(De_H instance);
    partial void UpdateDe_H(De_H instance);
    partial void DeleteDe_H(De_H instance);
    #endregion
		
		public DataTracNghiemDataContext() : 
				base(global::DoAnThiTracNghiem_Son.Properties.Settings.Default.TracNghiemConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataTracNghiemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTracNghiemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTracNghiemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTracNghiemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChuDe> ChuDes
		{
			get
			{
				return this.GetTable<ChuDe>();
			}
		}
		
		public System.Data.Linq.Table<CauHoi> CauHois
		{
			get
			{
				return this.GetTable<CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<DeThi> DeThis
		{
			get
			{
				return this.GetTable<DeThi>();
			}
		}
		
		public System.Data.Linq.Table<taiKhoan> taiKhoans
		{
			get
			{
				return this.GetTable<taiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<BatDau> BatDaus
		{
			get
			{
				return this.GetTable<BatDau>();
			}
		}
		
		public System.Data.Linq.Table<Khoi> Khois
		{
			get
			{
				return this.GetTable<Khoi>();
			}
		}
		
		public System.Data.Linq.Table<Nien_khoa> Nien_khoas
		{
			get
			{
				return this.GetTable<Nien_khoa>();
			}
		}
		
		public System.Data.Linq.Table<TaiKoan_H> TaiKoan_Hs
		{
			get
			{
				return this.GetTable<TaiKoan_H>();
			}
		}
		
		public System.Data.Linq.Table<De_H> De_Hs
		{
			get
			{
				return this.GetTable<De_H>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuDe")]
	public partial class ChuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten_Chu_De;
		
		private EntitySet<CauHoi> _CauHois;
		
		private EntitySet<DeThi> _DeThis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTen_Chu_DeChanging(string value);
    partial void OnTen_Chu_DeChanged();
    #endregion
		
		public ChuDe()
		{
			this._CauHois = new EntitySet<CauHoi>(new Action<CauHoi>(this.attach_CauHois), new Action<CauHoi>(this.detach_CauHois));
			this._DeThis = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis), new Action<DeThi>(this.detach_DeThis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Chu_De", DbType="NVarChar(300)")]
		public string Ten_Chu_De
		{
			get
			{
				return this._Ten_Chu_De;
			}
			set
			{
				if ((this._Ten_Chu_De != value))
				{
					this.OnTen_Chu_DeChanging(value);
					this.SendPropertyChanging();
					this._Ten_Chu_De = value;
					this.SendPropertyChanged("Ten_Chu_De");
					this.OnTen_Chu_DeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuDe_CauHoi", Storage="_CauHois", ThisKey="ID", OtherKey="Ma_Chu_De")]
		public EntitySet<CauHoi> CauHois
		{
			get
			{
				return this._CauHois;
			}
			set
			{
				this._CauHois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuDe_DeThi", Storage="_DeThis", ThisKey="ID", OtherKey="Ma_Chu_De")]
		public EntitySet<DeThi> DeThis
		{
			get
			{
				return this._DeThis;
			}
			set
			{
				this._DeThis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.ChuDe = this;
		}
		
		private void detach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.ChuDe = null;
		}
		
		private void attach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.ChuDe = this;
		}
		
		private void detach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.ChuDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi")]
	public partial class CauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Ma_Chu_De;
		
		private string _Tieu_De;
		
		private string _Noi_Dung;
		
		private string _Dap_An_A;
		
		private string _Dap_An_B;
		
		private string _Dap_An_C;
		
		private string _Dap_An_D;
		
		private System.Nullable<char> _Dap_An_Dung;
		
		private System.Nullable<char> _Cap_Do;
		
		private string _Nguoi_Tao;
		
		private string _Nguoi_Sua;
		
		private EntityRef<ChuDe> _ChuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMa_Chu_DeChanging(int value);
    partial void OnMa_Chu_DeChanged();
    partial void OnTieu_DeChanging(string value);
    partial void OnTieu_DeChanged();
    partial void OnNoi_DungChanging(string value);
    partial void OnNoi_DungChanged();
    partial void OnDap_An_AChanging(string value);
    partial void OnDap_An_AChanged();
    partial void OnDap_An_BChanging(string value);
    partial void OnDap_An_BChanged();
    partial void OnDap_An_CChanging(string value);
    partial void OnDap_An_CChanged();
    partial void OnDap_An_DChanging(string value);
    partial void OnDap_An_DChanged();
    partial void OnDap_An_DungChanging(System.Nullable<char> value);
    partial void OnDap_An_DungChanged();
    partial void OnCap_DoChanging(System.Nullable<char> value);
    partial void OnCap_DoChanged();
    partial void OnNguoi_TaoChanging(string value);
    partial void OnNguoi_TaoChanged();
    partial void OnNguoi_SuaChanging(string value);
    partial void OnNguoi_SuaChanged();
    #endregion
		
		public CauHoi()
		{
			this._ChuDe = default(EntityRef<ChuDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chu_De", DbType="Int NOT NULL")]
		public int Ma_Chu_De
		{
			get
			{
				return this._Ma_Chu_De;
			}
			set
			{
				if ((this._Ma_Chu_De != value))
				{
					if (this._ChuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Chu_DeChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chu_De = value;
					this.SendPropertyChanged("Ma_Chu_De");
					this.OnMa_Chu_DeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieu_De", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Tieu_De
		{
			get
			{
				return this._Tieu_De;
			}
			set
			{
				if ((this._Tieu_De != value))
				{
					this.OnTieu_DeChanging(value);
					this.SendPropertyChanging();
					this._Tieu_De = value;
					this.SendPropertyChanged("Tieu_De");
					this.OnTieu_DeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_Dung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Noi_Dung
		{
			get
			{
				return this._Noi_Dung;
			}
			set
			{
				if ((this._Noi_Dung != value))
				{
					this.OnNoi_DungChanging(value);
					this.SendPropertyChanging();
					this._Noi_Dung = value;
					this.SendPropertyChanged("Noi_Dung");
					this.OnNoi_DungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_A", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Dap_An_A
		{
			get
			{
				return this._Dap_An_A;
			}
			set
			{
				if ((this._Dap_An_A != value))
				{
					this.OnDap_An_AChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_A = value;
					this.SendPropertyChanged("Dap_An_A");
					this.OnDap_An_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_B", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Dap_An_B
		{
			get
			{
				return this._Dap_An_B;
			}
			set
			{
				if ((this._Dap_An_B != value))
				{
					this.OnDap_An_BChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_B = value;
					this.SendPropertyChanged("Dap_An_B");
					this.OnDap_An_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_C", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Dap_An_C
		{
			get
			{
				return this._Dap_An_C;
			}
			set
			{
				if ((this._Dap_An_C != value))
				{
					this.OnDap_An_CChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_C = value;
					this.SendPropertyChanged("Dap_An_C");
					this.OnDap_An_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_D", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Dap_An_D
		{
			get
			{
				return this._Dap_An_D;
			}
			set
			{
				if ((this._Dap_An_D != value))
				{
					this.OnDap_An_DChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_D = value;
					this.SendPropertyChanged("Dap_An_D");
					this.OnDap_An_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_Dung", DbType="Char(1)")]
		public System.Nullable<char> Dap_An_Dung
		{
			get
			{
				return this._Dap_An_Dung;
			}
			set
			{
				if ((this._Dap_An_Dung != value))
				{
					this.OnDap_An_DungChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_Dung = value;
					this.SendPropertyChanged("Dap_An_Dung");
					this.OnDap_An_DungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap_Do", DbType="Char(1)")]
		public System.Nullable<char> Cap_Do
		{
			get
			{
				return this._Cap_Do;
			}
			set
			{
				if ((this._Cap_Do != value))
				{
					this.OnCap_DoChanging(value);
					this.SendPropertyChanging();
					this._Cap_Do = value;
					this.SendPropertyChanged("Cap_Do");
					this.OnCap_DoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoi_Tao", DbType="NVarChar(50)")]
		public string Nguoi_Tao
		{
			get
			{
				return this._Nguoi_Tao;
			}
			set
			{
				if ((this._Nguoi_Tao != value))
				{
					this.OnNguoi_TaoChanging(value);
					this.SendPropertyChanging();
					this._Nguoi_Tao = value;
					this.SendPropertyChanged("Nguoi_Tao");
					this.OnNguoi_TaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoi_Sua", DbType="NVarChar(50)")]
		public string Nguoi_Sua
		{
			get
			{
				return this._Nguoi_Sua;
			}
			set
			{
				if ((this._Nguoi_Sua != value))
				{
					this.OnNguoi_SuaChanging(value);
					this.SendPropertyChanging();
					this._Nguoi_Sua = value;
					this.SendPropertyChanged("Nguoi_Sua");
					this.OnNguoi_SuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuDe_CauHoi", Storage="_ChuDe", ThisKey="Ma_Chu_De", OtherKey="ID", IsForeignKey=true)]
		public ChuDe ChuDe
		{
			get
			{
				return this._ChuDe.Entity;
			}
			set
			{
				ChuDe previousValue = this._ChuDe.Entity;
				if (((previousValue != value) 
							|| (this._ChuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuDe.Entity = null;
						previousValue.CauHois.Remove(this);
					}
					this._ChuDe.Entity = value;
					if ((value != null))
					{
						value.CauHois.Add(this);
						this._Ma_Chu_De = value.ID;
					}
					else
					{
						this._Ma_Chu_De = default(int);
					}
					this.SendPropertyChanged("ChuDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeThi")]
	public partial class DeThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Tieu_De;
		
		private int _Ma_Chu_De;
		
		private System.Nullable<int> _SL_De;
		
		private System.Nullable<int> _SL_TrungBinh;
		
		private System.Nullable<int> _SL_Kho;
		
		private System.Nullable<int> _Thoi_Gian_Lam_Bai;
		
		private string _Nguoi_Tao;
		
		private System.Nullable<System.DateTime> _Ngay_Tao;
		
		private System.Nullable<bool> _Trang_Thai;
		
		private EntitySet<BatDau> _BatDaus;
		
		private EntitySet<De_H> _De_Hs;
		
		private EntityRef<ChuDe> _ChuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTieu_DeChanging(string value);
    partial void OnTieu_DeChanged();
    partial void OnMa_Chu_DeChanging(int value);
    partial void OnMa_Chu_DeChanged();
    partial void OnSL_DeChanging(System.Nullable<int> value);
    partial void OnSL_DeChanged();
    partial void OnSL_TrungBinhChanging(System.Nullable<int> value);
    partial void OnSL_TrungBinhChanged();
    partial void OnSL_KhoChanging(System.Nullable<int> value);
    partial void OnSL_KhoChanged();
    partial void OnThoi_Gian_Lam_BaiChanging(System.Nullable<int> value);
    partial void OnThoi_Gian_Lam_BaiChanged();
    partial void OnNguoi_TaoChanging(string value);
    partial void OnNguoi_TaoChanged();
    partial void OnNgay_TaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_TaoChanged();
    partial void OnTrang_ThaiChanging(System.Nullable<bool> value);
    partial void OnTrang_ThaiChanged();
    #endregion
		
		public DeThi()
		{
			this._BatDaus = new EntitySet<BatDau>(new Action<BatDau>(this.attach_BatDaus), new Action<BatDau>(this.detach_BatDaus));
			this._De_Hs = new EntitySet<De_H>(new Action<De_H>(this.attach_De_Hs), new Action<De_H>(this.detach_De_Hs));
			this._ChuDe = default(EntityRef<ChuDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieu_De", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Tieu_De
		{
			get
			{
				return this._Tieu_De;
			}
			set
			{
				if ((this._Tieu_De != value))
				{
					this.OnTieu_DeChanging(value);
					this.SendPropertyChanging();
					this._Tieu_De = value;
					this.SendPropertyChanged("Tieu_De");
					this.OnTieu_DeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chu_De", DbType="Int NOT NULL")]
		public int Ma_Chu_De
		{
			get
			{
				return this._Ma_Chu_De;
			}
			set
			{
				if ((this._Ma_Chu_De != value))
				{
					if (this._ChuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Chu_DeChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chu_De = value;
					this.SendPropertyChanged("Ma_Chu_De");
					this.OnMa_Chu_DeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_De", DbType="Int")]
		public System.Nullable<int> SL_De
		{
			get
			{
				return this._SL_De;
			}
			set
			{
				if ((this._SL_De != value))
				{
					this.OnSL_DeChanging(value);
					this.SendPropertyChanging();
					this._SL_De = value;
					this.SendPropertyChanged("SL_De");
					this.OnSL_DeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_TrungBinh", DbType="Int")]
		public System.Nullable<int> SL_TrungBinh
		{
			get
			{
				return this._SL_TrungBinh;
			}
			set
			{
				if ((this._SL_TrungBinh != value))
				{
					this.OnSL_TrungBinhChanging(value);
					this.SendPropertyChanging();
					this._SL_TrungBinh = value;
					this.SendPropertyChanged("SL_TrungBinh");
					this.OnSL_TrungBinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_Kho", DbType="Int")]
		public System.Nullable<int> SL_Kho
		{
			get
			{
				return this._SL_Kho;
			}
			set
			{
				if ((this._SL_Kho != value))
				{
					this.OnSL_KhoChanging(value);
					this.SendPropertyChanging();
					this._SL_Kho = value;
					this.SendPropertyChanged("SL_Kho");
					this.OnSL_KhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_Gian_Lam_Bai", DbType="Int")]
		public System.Nullable<int> Thoi_Gian_Lam_Bai
		{
			get
			{
				return this._Thoi_Gian_Lam_Bai;
			}
			set
			{
				if ((this._Thoi_Gian_Lam_Bai != value))
				{
					this.OnThoi_Gian_Lam_BaiChanging(value);
					this.SendPropertyChanging();
					this._Thoi_Gian_Lam_Bai = value;
					this.SendPropertyChanged("Thoi_Gian_Lam_Bai");
					this.OnThoi_Gian_Lam_BaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoi_Tao", DbType="NVarChar(50)")]
		public string Nguoi_Tao
		{
			get
			{
				return this._Nguoi_Tao;
			}
			set
			{
				if ((this._Nguoi_Tao != value))
				{
					this.OnNguoi_TaoChanging(value);
					this.SendPropertyChanging();
					this._Nguoi_Tao = value;
					this.SendPropertyChanged("Nguoi_Tao");
					this.OnNguoi_TaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_Tao
		{
			get
			{
				return this._Ngay_Tao;
			}
			set
			{
				if ((this._Ngay_Tao != value))
				{
					this.OnNgay_TaoChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Tao = value;
					this.SendPropertyChanged("Ngay_Tao");
					this.OnNgay_TaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trang_Thai", DbType="Bit")]
		public System.Nullable<bool> Trang_Thai
		{
			get
			{
				return this._Trang_Thai;
			}
			set
			{
				if ((this._Trang_Thai != value))
				{
					this.OnTrang_ThaiChanging(value);
					this.SendPropertyChanging();
					this._Trang_Thai = value;
					this.SendPropertyChanged("Trang_Thai");
					this.OnTrang_ThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_BatDau", Storage="_BatDaus", ThisKey="id", OtherKey="Ma_DeThi")]
		public EntitySet<BatDau> BatDaus
		{
			get
			{
				return this._BatDaus;
			}
			set
			{
				this._BatDaus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_De_H", Storage="_De_Hs", ThisKey="id", OtherKey="Ma_Chu_De")]
		public EntitySet<De_H> De_Hs
		{
			get
			{
				return this._De_Hs;
			}
			set
			{
				this._De_Hs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuDe_DeThi", Storage="_ChuDe", ThisKey="Ma_Chu_De", OtherKey="ID", IsForeignKey=true)]
		public ChuDe ChuDe
		{
			get
			{
				return this._ChuDe.Entity;
			}
			set
			{
				ChuDe previousValue = this._ChuDe.Entity;
				if (((previousValue != value) 
							|| (this._ChuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuDe.Entity = null;
						previousValue.DeThis.Remove(this);
					}
					this._ChuDe.Entity = value;
					if ((value != null))
					{
						value.DeThis.Add(this);
						this._Ma_Chu_De = value.ID;
					}
					else
					{
						this._Ma_Chu_De = default(int);
					}
					this.SendPropertyChanged("ChuDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BatDaus(BatDau entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = this;
		}
		
		private void detach_BatDaus(BatDau entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = null;
		}
		
		private void attach_De_Hs(De_H entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = this;
		}
		
		private void detach_De_Hs(De_H entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taiKhoan")]
	public partial class taiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _HoTen;
		
		private string _userName;
		
		private string _pass;
		
		private System.Nullable<int> _phanQuyen;
		
		private string _thongTin;
		
		private EntitySet<TaiKoan_H> _TaiKoan_Hs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OnphanQuyenChanging(System.Nullable<int> value);
    partial void OnphanQuyenChanged();
    partial void OnthongTinChanging(string value);
    partial void OnthongTinChanged();
    #endregion
		
		public taiKhoan()
		{
			this._TaiKoan_Hs = new EntitySet<TaiKoan_H>(new Action<TaiKoan_H>(this.attach_TaiKoan_Hs), new Action<TaiKoan_H>(this.detach_TaiKoan_Hs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(80)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(50)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phanQuyen", DbType="Int")]
		public System.Nullable<int> phanQuyen
		{
			get
			{
				return this._phanQuyen;
			}
			set
			{
				if ((this._phanQuyen != value))
				{
					this.OnphanQuyenChanging(value);
					this.SendPropertyChanging();
					this._phanQuyen = value;
					this.SendPropertyChanged("phanQuyen");
					this.OnphanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thongTin", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string thongTin
		{
			get
			{
				return this._thongTin;
			}
			set
			{
				if ((this._thongTin != value))
				{
					this.OnthongTinChanging(value);
					this.SendPropertyChanging();
					this._thongTin = value;
					this.SendPropertyChanged("thongTin");
					this.OnthongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taiKhoan_TaiKoan_H", Storage="_TaiKoan_Hs", ThisKey="id", OtherKey="id_TaiKhoan")]
		public EntitySet<TaiKoan_H> TaiKoan_Hs
		{
			get
			{
				return this._TaiKoan_Hs;
			}
			set
			{
				this._TaiKoan_Hs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKoan_Hs(TaiKoan_H entity)
		{
			this.SendPropertyChanging();
			entity.taiKhoan = this;
		}
		
		private void detach_TaiKoan_Hs(TaiKoan_H entity)
		{
			this.SendPropertyChanging();
			entity.taiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BatDau")]
	public partial class BatDau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Ma_DeThi;
		
		private string _Nguoi_Lam;
		
		private System.Nullable<System.DateTime> _Thoi_Gian;
		
		private System.Nullable<bool> _Nop_Bai;
		
		private EntityRef<DeThi> _DeThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMa_DeThiChanging(int value);
    partial void OnMa_DeThiChanged();
    partial void OnNguoi_LamChanging(string value);
    partial void OnNguoi_LamChanged();
    partial void OnThoi_GianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoi_GianChanged();
    partial void OnNop_BaiChanging(System.Nullable<bool> value);
    partial void OnNop_BaiChanged();
    #endregion
		
		public BatDau()
		{
			this._DeThi = default(EntityRef<DeThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_DeThi", DbType="Int NOT NULL")]
		public int Ma_DeThi
		{
			get
			{
				return this._Ma_DeThi;
			}
			set
			{
				if ((this._Ma_DeThi != value))
				{
					if (this._DeThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_DeThiChanging(value);
					this.SendPropertyChanging();
					this._Ma_DeThi = value;
					this.SendPropertyChanged("Ma_DeThi");
					this.OnMa_DeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoi_Lam", DbType="NVarChar(50)")]
		public string Nguoi_Lam
		{
			get
			{
				return this._Nguoi_Lam;
			}
			set
			{
				if ((this._Nguoi_Lam != value))
				{
					this.OnNguoi_LamChanging(value);
					this.SendPropertyChanging();
					this._Nguoi_Lam = value;
					this.SendPropertyChanged("Nguoi_Lam");
					this.OnNguoi_LamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_Gian", DbType="DateTime")]
		public System.Nullable<System.DateTime> Thoi_Gian
		{
			get
			{
				return this._Thoi_Gian;
			}
			set
			{
				if ((this._Thoi_Gian != value))
				{
					this.OnThoi_GianChanging(value);
					this.SendPropertyChanging();
					this._Thoi_Gian = value;
					this.SendPropertyChanged("Thoi_Gian");
					this.OnThoi_GianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nop_Bai", DbType="Bit")]
		public System.Nullable<bool> Nop_Bai
		{
			get
			{
				return this._Nop_Bai;
			}
			set
			{
				if ((this._Nop_Bai != value))
				{
					this.OnNop_BaiChanging(value);
					this.SendPropertyChanging();
					this._Nop_Bai = value;
					this.SendPropertyChanged("Nop_Bai");
					this.OnNop_BaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_BatDau", Storage="_DeThi", ThisKey="Ma_DeThi", OtherKey="id", IsForeignKey=true)]
		public DeThi DeThi
		{
			get
			{
				return this._DeThi.Entity;
			}
			set
			{
				DeThi previousValue = this._DeThi.Entity;
				if (((previousValue != value) 
							|| (this._DeThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeThi.Entity = null;
						previousValue.BatDaus.Remove(this);
					}
					this._DeThi.Entity = value;
					if ((value != null))
					{
						value.BatDaus.Add(this);
						this._Ma_DeThi = value.id;
					}
					else
					{
						this._Ma_DeThi = default(int);
					}
					this.SendPropertyChanged("DeThi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoi")]
	public partial class Khoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _khoi1;
		
		private EntitySet<TaiKoan_H> _TaiKoan_Hs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onkhoi1Changing(string value);
    partial void Onkhoi1Changed();
    #endregion
		
		public Khoi()
		{
			this._TaiKoan_Hs = new EntitySet<TaiKoan_H>(new Action<TaiKoan_H>(this.attach_TaiKoan_Hs), new Action<TaiKoan_H>(this.detach_TaiKoan_Hs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="khoi", Storage="_khoi1", DbType="NVarChar(20)")]
		public string khoi1
		{
			get
			{
				return this._khoi1;
			}
			set
			{
				if ((this._khoi1 != value))
				{
					this.Onkhoi1Changing(value);
					this.SendPropertyChanging();
					this._khoi1 = value;
					this.SendPropertyChanged("khoi1");
					this.Onkhoi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoi_TaiKoan_H", Storage="_TaiKoan_Hs", ThisKey="id", OtherKey="id_khoi")]
		public EntitySet<TaiKoan_H> TaiKoan_Hs
		{
			get
			{
				return this._TaiKoan_Hs;
			}
			set
			{
				this._TaiKoan_Hs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKoan_Hs(TaiKoan_H entity)
		{
			this.SendPropertyChanging();
			entity.Khoi = this;
		}
		
		private void detach_TaiKoan_Hs(TaiKoan_H entity)
		{
			this.SendPropertyChanging();
			entity.Khoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nien_khoa")]
	public partial class Nien_khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nien_khoa1;
		
		private EntitySet<TaiKoan_H> _TaiKoan_Hs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnien_khoa1Changing(string value);
    partial void Onnien_khoa1Changed();
    #endregion
		
		public Nien_khoa()
		{
			this._TaiKoan_Hs = new EntitySet<TaiKoan_H>(new Action<TaiKoan_H>(this.attach_TaiKoan_Hs), new Action<TaiKoan_H>(this.detach_TaiKoan_Hs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nien_khoa", Storage="_nien_khoa1", DbType="NVarChar(20)")]
		public string nien_khoa1
		{
			get
			{
				return this._nien_khoa1;
			}
			set
			{
				if ((this._nien_khoa1 != value))
				{
					this.Onnien_khoa1Changing(value);
					this.SendPropertyChanging();
					this._nien_khoa1 = value;
					this.SendPropertyChanged("nien_khoa1");
					this.Onnien_khoa1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nien_khoa_TaiKoan_H", Storage="_TaiKoan_Hs", ThisKey="id", OtherKey="id_nien_khoa")]
		public EntitySet<TaiKoan_H> TaiKoan_Hs
		{
			get
			{
				return this._TaiKoan_Hs;
			}
			set
			{
				this._TaiKoan_Hs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKoan_Hs(TaiKoan_H entity)
		{
			this.SendPropertyChanging();
			entity.Nien_khoa = this;
		}
		
		private void detach_TaiKoan_Hs(TaiKoan_H entity)
		{
			this.SendPropertyChanging();
			entity.Nien_khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKoan_HS")]
	public partial class TaiKoan_H : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_khoi;
		
		private int _id_nien_khoa;
		
		private int _id_TaiKhoan;
		
		private string _lop;
		
		private EntitySet<De_H> _De_Hs;
		
		private EntityRef<Nien_khoa> _Nien_khoa;
		
		private EntityRef<Khoi> _Khoi;
		
		private EntityRef<taiKhoan> _taiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_khoiChanging(int value);
    partial void Onid_khoiChanged();
    partial void Onid_nien_khoaChanging(int value);
    partial void Onid_nien_khoaChanged();
    partial void Onid_TaiKhoanChanging(int value);
    partial void Onid_TaiKhoanChanged();
    partial void OnlopChanging(string value);
    partial void OnlopChanged();
    #endregion
		
		public TaiKoan_H()
		{
			this._De_Hs = new EntitySet<De_H>(new Action<De_H>(this.attach_De_Hs), new Action<De_H>(this.detach_De_Hs));
			this._Nien_khoa = default(EntityRef<Nien_khoa>);
			this._Khoi = default(EntityRef<Khoi>);
			this._taiKhoan = default(EntityRef<taiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khoi", DbType="Int NOT NULL")]
		public int id_khoi
		{
			get
			{
				return this._id_khoi;
			}
			set
			{
				if ((this._id_khoi != value))
				{
					if (this._Khoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khoiChanging(value);
					this.SendPropertyChanging();
					this._id_khoi = value;
					this.SendPropertyChanged("id_khoi");
					this.Onid_khoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nien_khoa", DbType="Int NOT NULL")]
		public int id_nien_khoa
		{
			get
			{
				return this._id_nien_khoa;
			}
			set
			{
				if ((this._id_nien_khoa != value))
				{
					if (this._Nien_khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nien_khoaChanging(value);
					this.SendPropertyChanging();
					this._id_nien_khoa = value;
					this.SendPropertyChanged("id_nien_khoa");
					this.Onid_nien_khoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_TaiKhoan", DbType="Int NOT NULL")]
		public int id_TaiKhoan
		{
			get
			{
				return this._id_TaiKhoan;
			}
			set
			{
				if ((this._id_TaiKhoan != value))
				{
					if (this._taiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_TaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._id_TaiKhoan = value;
					this.SendPropertyChanged("id_TaiKhoan");
					this.Onid_TaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NVarChar(10)")]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this.OnlopChanging(value);
					this.SendPropertyChanging();
					this._lop = value;
					this.SendPropertyChanged("lop");
					this.OnlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKoan_H_De_H", Storage="_De_Hs", ThisKey="id", OtherKey="id_Tai_Khoan_HS")]
		public EntitySet<De_H> De_Hs
		{
			get
			{
				return this._De_Hs;
			}
			set
			{
				this._De_Hs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nien_khoa_TaiKoan_H", Storage="_Nien_khoa", ThisKey="id_nien_khoa", OtherKey="id", IsForeignKey=true)]
		public Nien_khoa Nien_khoa
		{
			get
			{
				return this._Nien_khoa.Entity;
			}
			set
			{
				Nien_khoa previousValue = this._Nien_khoa.Entity;
				if (((previousValue != value) 
							|| (this._Nien_khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nien_khoa.Entity = null;
						previousValue.TaiKoan_Hs.Remove(this);
					}
					this._Nien_khoa.Entity = value;
					if ((value != null))
					{
						value.TaiKoan_Hs.Add(this);
						this._id_nien_khoa = value.id;
					}
					else
					{
						this._id_nien_khoa = default(int);
					}
					this.SendPropertyChanged("Nien_khoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoi_TaiKoan_H", Storage="_Khoi", ThisKey="id_khoi", OtherKey="id", IsForeignKey=true)]
		public Khoi Khoi
		{
			get
			{
				return this._Khoi.Entity;
			}
			set
			{
				Khoi previousValue = this._Khoi.Entity;
				if (((previousValue != value) 
							|| (this._Khoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoi.Entity = null;
						previousValue.TaiKoan_Hs.Remove(this);
					}
					this._Khoi.Entity = value;
					if ((value != null))
					{
						value.TaiKoan_Hs.Add(this);
						this._id_khoi = value.id;
					}
					else
					{
						this._id_khoi = default(int);
					}
					this.SendPropertyChanged("Khoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taiKhoan_TaiKoan_H", Storage="_taiKhoan", ThisKey="id_TaiKhoan", OtherKey="id", IsForeignKey=true)]
		public taiKhoan taiKhoan
		{
			get
			{
				return this._taiKhoan.Entity;
			}
			set
			{
				taiKhoan previousValue = this._taiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._taiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._taiKhoan.Entity = null;
						previousValue.TaiKoan_Hs.Remove(this);
					}
					this._taiKhoan.Entity = value;
					if ((value != null))
					{
						value.TaiKoan_Hs.Add(this);
						this._id_TaiKhoan = value.id;
					}
					else
					{
						this._id_TaiKhoan = default(int);
					}
					this.SendPropertyChanged("taiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_De_Hs(De_H entity)
		{
			this.SendPropertyChanging();
			entity.TaiKoan_H = this;
		}
		
		private void detach_De_Hs(De_H entity)
		{
			this.SendPropertyChanging();
			entity.TaiKoan_H = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.De_HS")]
	public partial class De_H : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Ma_Chu_De;
		
		private string _Noi_Dung;
		
		private string _Dap_An_A;
		
		private string _Dap_An_B;
		
		private string _Dap_An_C;
		
		private string _Dap_An_D;
		
		private System.Nullable<char> _Dap_An_Dung;
		
		private System.Nullable<char> _Dap_An_HS;
		
		private string _Nguoi_Lam;
		
		private System.Nullable<System.DateTime> _Thoi_Gian;
		
		private System.Nullable<int> _id_Tai_Khoan_HS;
		
		private EntityRef<DeThi> _DeThi;
		
		private EntityRef<TaiKoan_H> _TaiKoan_H;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMa_Chu_DeChanging(int value);
    partial void OnMa_Chu_DeChanged();
    partial void OnNoi_DungChanging(string value);
    partial void OnNoi_DungChanged();
    partial void OnDap_An_AChanging(string value);
    partial void OnDap_An_AChanged();
    partial void OnDap_An_BChanging(string value);
    partial void OnDap_An_BChanged();
    partial void OnDap_An_CChanging(string value);
    partial void OnDap_An_CChanged();
    partial void OnDap_An_DChanging(string value);
    partial void OnDap_An_DChanged();
    partial void OnDap_An_DungChanging(System.Nullable<char> value);
    partial void OnDap_An_DungChanged();
    partial void OnDap_An_HSChanging(System.Nullable<char> value);
    partial void OnDap_An_HSChanged();
    partial void OnNguoi_LamChanging(string value);
    partial void OnNguoi_LamChanged();
    partial void OnThoi_GianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoi_GianChanged();
    partial void Onid_Tai_Khoan_HSChanging(System.Nullable<int> value);
    partial void Onid_Tai_Khoan_HSChanged();
    #endregion
		
		public De_H()
		{
			this._DeThi = default(EntityRef<DeThi>);
			this._TaiKoan_H = default(EntityRef<TaiKoan_H>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chu_De", DbType="Int NOT NULL")]
		public int Ma_Chu_De
		{
			get
			{
				return this._Ma_Chu_De;
			}
			set
			{
				if ((this._Ma_Chu_De != value))
				{
					if (this._DeThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Chu_DeChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chu_De = value;
					this.SendPropertyChanged("Ma_Chu_De");
					this.OnMa_Chu_DeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_Dung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Noi_Dung
		{
			get
			{
				return this._Noi_Dung;
			}
			set
			{
				if ((this._Noi_Dung != value))
				{
					this.OnNoi_DungChanging(value);
					this.SendPropertyChanging();
					this._Noi_Dung = value;
					this.SendPropertyChanged("Noi_Dung");
					this.OnNoi_DungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_A", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Dap_An_A
		{
			get
			{
				return this._Dap_An_A;
			}
			set
			{
				if ((this._Dap_An_A != value))
				{
					this.OnDap_An_AChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_A = value;
					this.SendPropertyChanged("Dap_An_A");
					this.OnDap_An_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_B", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Dap_An_B
		{
			get
			{
				return this._Dap_An_B;
			}
			set
			{
				if ((this._Dap_An_B != value))
				{
					this.OnDap_An_BChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_B = value;
					this.SendPropertyChanged("Dap_An_B");
					this.OnDap_An_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_C", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Dap_An_C
		{
			get
			{
				return this._Dap_An_C;
			}
			set
			{
				if ((this._Dap_An_C != value))
				{
					this.OnDap_An_CChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_C = value;
					this.SendPropertyChanged("Dap_An_C");
					this.OnDap_An_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_D", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Dap_An_D
		{
			get
			{
				return this._Dap_An_D;
			}
			set
			{
				if ((this._Dap_An_D != value))
				{
					this.OnDap_An_DChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_D = value;
					this.SendPropertyChanged("Dap_An_D");
					this.OnDap_An_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_Dung", DbType="Char(1)")]
		public System.Nullable<char> Dap_An_Dung
		{
			get
			{
				return this._Dap_An_Dung;
			}
			set
			{
				if ((this._Dap_An_Dung != value))
				{
					this.OnDap_An_DungChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_Dung = value;
					this.SendPropertyChanged("Dap_An_Dung");
					this.OnDap_An_DungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dap_An_HS", DbType="Char(1)")]
		public System.Nullable<char> Dap_An_HS
		{
			get
			{
				return this._Dap_An_HS;
			}
			set
			{
				if ((this._Dap_An_HS != value))
				{
					this.OnDap_An_HSChanging(value);
					this.SendPropertyChanging();
					this._Dap_An_HS = value;
					this.SendPropertyChanged("Dap_An_HS");
					this.OnDap_An_HSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoi_Lam", DbType="NVarChar(50)")]
		public string Nguoi_Lam
		{
			get
			{
				return this._Nguoi_Lam;
			}
			set
			{
				if ((this._Nguoi_Lam != value))
				{
					this.OnNguoi_LamChanging(value);
					this.SendPropertyChanging();
					this._Nguoi_Lam = value;
					this.SendPropertyChanged("Nguoi_Lam");
					this.OnNguoi_LamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_Gian", DbType="DateTime")]
		public System.Nullable<System.DateTime> Thoi_Gian
		{
			get
			{
				return this._Thoi_Gian;
			}
			set
			{
				if ((this._Thoi_Gian != value))
				{
					this.OnThoi_GianChanging(value);
					this.SendPropertyChanging();
					this._Thoi_Gian = value;
					this.SendPropertyChanged("Thoi_Gian");
					this.OnThoi_GianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Tai_Khoan_HS", DbType="Int")]
		public System.Nullable<int> id_Tai_Khoan_HS
		{
			get
			{
				return this._id_Tai_Khoan_HS;
			}
			set
			{
				if ((this._id_Tai_Khoan_HS != value))
				{
					if (this._TaiKoan_H.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_Tai_Khoan_HSChanging(value);
					this.SendPropertyChanging();
					this._id_Tai_Khoan_HS = value;
					this.SendPropertyChanged("id_Tai_Khoan_HS");
					this.Onid_Tai_Khoan_HSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_De_H", Storage="_DeThi", ThisKey="Ma_Chu_De", OtherKey="id", IsForeignKey=true)]
		public DeThi DeThi
		{
			get
			{
				return this._DeThi.Entity;
			}
			set
			{
				DeThi previousValue = this._DeThi.Entity;
				if (((previousValue != value) 
							|| (this._DeThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeThi.Entity = null;
						previousValue.De_Hs.Remove(this);
					}
					this._DeThi.Entity = value;
					if ((value != null))
					{
						value.De_Hs.Add(this);
						this._Ma_Chu_De = value.id;
					}
					else
					{
						this._Ma_Chu_De = default(int);
					}
					this.SendPropertyChanged("DeThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKoan_H_De_H", Storage="_TaiKoan_H", ThisKey="id_Tai_Khoan_HS", OtherKey="id", IsForeignKey=true)]
		public TaiKoan_H TaiKoan_H
		{
			get
			{
				return this._TaiKoan_H.Entity;
			}
			set
			{
				TaiKoan_H previousValue = this._TaiKoan_H.Entity;
				if (((previousValue != value) 
							|| (this._TaiKoan_H.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKoan_H.Entity = null;
						previousValue.De_Hs.Remove(this);
					}
					this._TaiKoan_H.Entity = value;
					if ((value != null))
					{
						value.De_Hs.Add(this);
						this._id_Tai_Khoan_HS = value.id;
					}
					else
					{
						this._id_Tai_Khoan_HS = default(Nullable<int>);
					}
					this.SendPropertyChanged("TaiKoan_H");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
